<?php

// Edit lines below to setup your database connection.
define("DB_SERVER", "mariadb");
define("DB_USER", "rootuser");
define("DB_PWD", "rootpass");
define("DB_NAME", "sqlinjection");

// Base path. Edit below if the simulation environment is not at the root of your webserver.
define("BASE_SIM_PATH", "/");		// Could be something like : "/simulation/"


// Misc.
define("SIM_VERSION", "1.00");
define("YEAR", "2012");
define("URL", "http://www.sqlinjection.net");
define("DISPLAY_URL", "SQLInjection.net");


?>
